In [2]:
import sys

In [3]:
#!pip install composable

In [4]:
import pandas as pd
from composable import pipeable

In [5]:
help(pd.Series.str.slice)

Help on function slice in module pandas.core.strings.accessor:

slice(self, start=None, stop=None, step=None)
    Slice substrings from each element in the Series or Index.
    
    Parameters
    ----------
    start : int, optional
        Start position for slice operation.
    stop : int, optional
        Stop position for slice operation.
    step : int, optional
        Step size for slice operation.
    
    Returns
    -------
    Series or Index of object
        Series or Index from sliced substring from original string object.
    
    See Also
    --------
    Series.str.slice_replace : Replace a slice with a string.
    Series.str.get : Return element at position.
        Equivalent to `Series.str.slice(start=i, stop=i+1)` with `i`
        being the position.
    
    Examples
    --------
    >>> s = pd.Series(["koala", "fox", "chameleon"])
    >>> s
    0        koala
    1          fox
    2    chameleon
    dtype: object
    
    >>> s.str.slice(start=1)
    0        o

In [6]:
@pipeable
def slice(col, start=None, stop=None, step=None):
    return col.str.slice( start = start, stop = stop, step = step)

In [7]:
from composable.strict import map
c = pd.Series(map(str, range(1000,1011)))
c

0     1000
1     1001
2     1002
3     1003
4     1004
5     1005
6     1006
7     1007
8     1008
9     1009
10    1010
dtype: object

In [8]:
c.str.slice(1, 3)

0     00
1     00
2     00
3     00
4     00
5     00
6     00
7     00
8     00
9     00
10    01
dtype: object

In [9]:
#c >> slice(1, 3) # first argument passed to `col` by position.

In [10]:
@pipeable
def slice(col, *, start=None, stop=None, step=None):
    return col.str.slice(start, stop, step)

In [11]:
c >> slice(start = 1, stop = 3) # second and third digits

0     00
1     00
2     00
3     00
4     00
5     00
6     00
7     00
8     00
9     00
10    01
dtype: object

In [12]:
#@pipeable
def replace(col, pat, rep1, n = -1, case = None, flags = 0, regex = none):
    return col.str.slice()

NameError: name 'none' is not defined

In [13]:
help(c.str.replace)

Help on method replace in module pandas.core.strings.accessor:

replace(pat, repl, n=-1, case=None, flags=0, regex=None) method of pandas.core.strings.accessor.StringMethods instance
    Replace each occurrence of pattern/regex in the Series/Index.
    
    Equivalent to :meth:`str.replace` or :func:`re.sub`, depending on
    the regex value.
    
    Parameters
    ----------
    pat : str or compiled regex
        String can be a character sequence or regular expression.
    repl : str or callable
        Replacement string or a callable. The callable is passed the regex
        match object and must return a replacement string to be used.
        See :func:`re.sub`.
    n : int, default -1 (all)
        Number of replacements to make from start.
    case : bool, default None
        Determines if replace is case sensitive:
    
        - If True, case sensitive (the default if `pat` is a string)
        - Set to False for case insensitive
        - Cannot be set if `pat` is a compil

In [69]:
[m for m in dir(pd.DatetimeIndex) if not m.startswith('_')]

['T',
 'all',
 'any',
 'append',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asi8',
 'asof',
 'asof_locs',
 'astype',
 'ceil',
 'copy',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'delete',
 'difference',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'duplicated',
 'empty',
 'equals',
 'factorize',
 'fillna',
 'floor',
 'format',
 'freq',
 'freqstr',
 'get_indexer',
 'get_indexer_for',
 'get_indexer_non_unique',
 'get_level_values',
 'get_loc',
 'get_slice_bound',
 'get_value',
 'groupby',
 'has_duplicates',
 'hasnans',
 'holds_integer',
 'hour',
 'identical',
 'indexer_at_time',
 'indexer_between_time',
 'inferred_freq',
 'inferred_type',
 'insert',
 'intersection',
 'is_',
 'is_all_dates',
 'is_boolean',
 'is_categorical',
 'is_floating',
 'is_integer',
 'is_interval',
 'is_leap_year',
 'is_mixed',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_month_en

In [70]:
help(pd.DatetimeIndex.is_leap_year)

Help on property:

    Boolean indicator if the date belongs to a leap year.
    
    A leap year is a year, which has 366 days (instead of 365) including
    29th of February as an intercalary day.
    Leap years are years which are multiples of four with the exception
    of years divisible by 100 but not by 400.
    
    Returns
    -------
    Series or ndarray
         Booleans indicating if dates belong to a leap year.
    
    Examples
    --------
    This method is available on Series with datetime values under
    the ``.dt`` accessor, and directly on DatetimeIndex.
    
    >>> idx = pd.date_range("2012-01-01", "2015-01-01", freq="Y")
    >>> idx
    DatetimeIndex(['2012-12-31', '2013-12-31', '2014-12-31'],
                  dtype='datetime64[ns]', freq='A-DEC')
    >>> idx.is_leap_year
    array([ True, False, False])
    
    >>> dates_series = pd.Series(idx)
    >>> dates_series
    0   2012-12-31
    1   2013-12-31
    2   2014-12-31
    dtype: datetime64[ns]
    >>> dat

In [71]:
help(pd.DatetimeIndex.is_interval)

Help on function is_interval in module pandas.core.indexes.base:

is_interval(self) -> bool
    Check if the Index holds Interval objects.
    
    Returns
    -------
    bool
        Whether or not the Index holds Interval objects.
    
    See Also
    --------
    IntervalIndex : Index for Interval objects.
    is_boolean : Check if the Index only consists of booleans.
    is_integer : Check if the Index only consists of integers.
    is_floating : Check if the Index is a floating type.
    is_numeric : Check if the Index only consists of numeric data.
    is_object : Check if the Index is of the object dtype.
    is_categorical : Check if the Index holds categorical data.
    is_mixed : Check if the Index holds data with mixed data types.
    
    Examples
    --------
    >>> idx = pd.Index([pd.Interval(left=0, right=5),
    ...                 pd.Interval(left=5, right=10)])
    >>> idx.is_interval()
    True
    
    >>> idx = pd.Index([1, 3, 5, 7])
    >>> idx.is_interval()
  

In [72]:
help(pd.DatetimeIndex.intersection)

Help on function intersection in module pandas.core.indexes.datetimelike:

intersection(self, other, sort=False)
    Specialized intersection for DatetimeIndex/TimedeltaIndex.
    
    May be much faster than Index.intersection
    
    Parameters
    ----------
    other : Same type as self or array-like
    sort : False or None, default False
        Sort the resulting index if possible.
    
        .. versionadded:: 0.24.0
    
        .. versionchanged:: 0.24.1
    
           Changed the default to ``False`` to match the behaviour
           from before 0.24.0.
    
        .. versionchanged:: 0.25.0
    
           The `sort` keyword is added
    
    Returns
    -------
    y : Index or same type as self



In [78]:
help(pd.DatetimeIndex.insert)



Help on function insert in module pandas.core.indexes.datetimelike:

insert(self, loc, item)
    Make new Index inserting new item at location. Follows
    Python list.append semantics for negative values.
    
    Parameters
    ----------
    loc : int
    item : object
    
    Returns
    -------
    new_index : Index
    
    Raises
    ------
    ValueError if the item is not valid for this dtype.



In [9]:
help(pd.DatetimeIndex.is_mixed)

Help on function is_mixed in module pandas.core.indexes.base:

is_mixed(self) -> bool
    Check if the Index holds data with mixed data types.
    
    Returns
    -------
    bool
        Whether or not the Index holds data with mixed data types.
    
    See Also
    --------
    is_boolean : Check if the Index only consists of booleans.
    is_integer : Check if the Index only consists of integers.
    is_floating : Check if the Index is a floating type.
    is_numeric : Check if the Index only consists of numeric data.
    is_object : Check if the Index is of the object dtype.
    is_categorical : Check if the Index holds categorical data.
    is_interval : Check if the Index holds Interval objects.
    
    Examples
    --------
    >>> idx = pd.Index(['a', np.nan, 'b'])
    >>> idx.is_mixed()
    True
    
    >>> idx = pd.Index([1.0, 2.0, 3.0, 5.0])
    >>> idx.is_mixed()
    False



In [13]:
help(pd.Series.dt.is_leap_year)

Help on property:

    Boolean indicator if the date belongs to a leap year.
    
    A leap year is a year, which has 366 days (instead of 365) including
    29th of February as an intercalary day.
    Leap years are years which are multiples of four with the exception
    of years divisible by 100 but not by 400.
    
    Returns
    -------
    Series or ndarray
         Booleans indicating if dates belong to a leap year.
    
    Examples
    --------
    This method is available on Series with datetime values under
    the ``.dt`` accessor, and directly on DatetimeIndex.
    
    >>> idx = pd.date_range("2012-01-01", "2015-01-01", freq="Y")
    >>> idx
    DatetimeIndex(['2012-12-31', '2013-12-31', '2014-12-31'],
                  dtype='datetime64[ns]', freq='A-DEC')
    >>> idx.is_leap_year
    array([ True, False, False])
    
    >>> dates_series = pd.Series(idx)
    >>> dates_series
    0   2012-12-31
    1   2013-12-31
    2   2014-12-31
    dtype: datetime64[ns]
    >>> dat

In [29]:
help(pd.Series.dt.tz)

Help on property:

    Return timezone, if any.
    
    Returns
    -------
    datetime.tzinfo, pytz.tzinfo.BaseTZInfo, dateutil.tz.tz.tzfile, or None
        Returns None when the array is tz-naive.



In [23]:
pd.Series.dt.is_leap_year("2012-01-01")

TypeError: 'property' object is not callable

In [12]:
[m for m in dir(pd.Series.dt) if not m.startswith('_')]

['asfreq',
 'ceil',
 'components',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days',
 'days_in_month',
 'daysinmonth',
 'end_time',
 'floor',
 'freq',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'microseconds',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'nanoseconds',
 'normalize',
 'quarter',
 'qyear',
 'round',
 'second',
 'seconds',
 'start_time',
 'strftime',
 'time',
 'timetz',
 'to_period',
 'to_pydatetime',
 'to_pytimedelta',
 'to_timestamp',
 'total_seconds',
 'tz',
 'tz_convert',
 'tz_localize',
 'week',
 'weekday',
 'weekofyear',
 'year']

In [88]:
help(pd.Series.dt.is_leap_year)

Help on property:

    Boolean indicator if the date belongs to a leap year.
    
    A leap year is a year, which has 366 days (instead of 365) including
    29th of February as an intercalary day.
    Leap years are years which are multiples of four with the exception
    of years divisible by 100 but not by 400.
    
    Returns
    -------
    Series or ndarray
         Booleans indicating if dates belong to a leap year.
    
    Examples
    --------
    This method is available on Series with datetime values under
    the ``.dt`` accessor, and directly on DatetimeIndex.
    
    >>> idx = pd.date_range("2012-01-01", "2015-01-01", freq="Y")
    >>> idx
    DatetimeIndex(['2012-12-31', '2013-12-31', '2014-12-31'],
                  dtype='datetime64[ns]', freq='A-DEC')
    >>> idx.is_leap_year
    array([ True, False, False])
    
    >>> dates_series = pd.Series(idx)
    >>> dates_series
    0   2012-12-31
    1   2013-12-31
    2   2014-12-31
    dtype: datetime64[ns]
    >>> dat

In [89]:
@pipeable
def is_leap_year(col):
    """Boolean indicator if the date belongs to a leap year.
    
    A leap year is a year, which has 366 days (instead of 365) including
    29th of February as an intercalary day.
    Leap years are years which are multiples of four with the exception
    of years divisible by 100 but not by 400.
    
    Returns
    -------
    Series or ndarray
         Booleans indicating if dates belong to a leap year.
    
    Examples
    --------
    This method is available on Series with datetime values under
    the ``.dt`` accessor, and directly on DatetimeIndex.
    
    >>> idx = pd.date_range("2012-01-01", "2015-01-01", freq="Y")
    >>> idx
    DatetimeIndex(['2012-12-31', '2013-12-31', '2014-12-31'],
                  dtype='datetime64[ns]', freq='A-DEC')
    >>> idx.is_leap_year
    array([ True, False, False])
    
    >>> dates_series = pd.Series(idx)
    >>> dates_series
    0   2012-12-31
    1   2013-12-31
    2   2014-12-31
    dtype: datetime64[ns]
    >>> dates_series.dt.is_leap_year
    0     True
    1    False
    2    False
    dtype: bool
    """
    return col.dt.is_leap_year

In [105]:
dt = pd.Series(pd.date_range("2000-01-05", periods=1, freq="Y"))
dt
dt >> is_leap_year()
assert (dt >> is_leap_year())[0]
type((dt >> is_leap_year())[0])
assert isinstance((dt >> is_leap_year())[0], numpy.bool_)

NameError: name 'numpy' is not defined

In [14]:
help(pd.Series.dt.minute)

Help on property:

    The minutes of the datetime.
    
    Examples
    --------
    >>> datetime_series = pd.Series(
    ...     pd.date_range("2000-01-01", periods=3, freq="T")
    ... )
    >>> datetime_series
    0   2000-01-01 00:00:00
    1   2000-01-01 00:01:00
    2   2000-01-01 00:02:00
    dtype: datetime64[ns]
    >>> datetime_series.dt.minute
    0    0
    1    1
    2    2
    dtype: int64



In [22]:
datetime_series = pd.Series(pd.date_range("2000-01-01", periods=3, freq="T"))
datetime_series.dt.minute[0]

0

In [31]:
@pipeable
def minute(col):
    """The minutes of the datetime.
    
    Examples
    --------
    >>> datetime_series = pd.Series(
    ...     pd.date_range("2000-01-01", periods=3, freq="T")
    ... )
    >>> datetime_series
    0   2000-01-01 00:00:00
    1   2000-01-01 00:01:00
    2   2000-01-01 00:02:00
    dtype: datetime64[ns]
    >>> datetime_series.dt.minute
    0    0
    1    1
    2    2
    dtype: int64

    """
    return col.dt.minute

In [33]:
result = pd.Series(pd.date_range("2000-01-01", periods=3, freq="T"))
exp = Series([0,1,2])
result >> minute()
tm.assert_series_equal(result >> minute(), exp)

In [34]:
result2 = pd.Series(pd.date_range("2000-01-01", periods=62, freq="T"))
result2 >> minute()

0      0
1      1
2      2
3      3
4      4
      ..
57    57
58    58
59    59
60     0
61     1
Length: 62, dtype: int64

In [26]:
from pandas import Series, _testing as tm

assert datetime_series.dt.minute[0] == 0

In [52]:
# roll over
roll = pd.Series(pd.date_range("2000-01-01 00:59:00", periods=3, freq="T"))
exp = Series([59,0,1])
tm.assert_series_equal(roll.tail(3) >> minute(), exp)
roll >> minute()



0    59
1     0
2     1
dtype: int64

In [21]:
import pandas.compat

pandas.compat

<module 'pandas.compat' from '/home/sandrews/.pyenv/versions/anaconda3-2020.02/lib/python3.7/site-packages/pandas/compat/__init__.py'>

In [54]:
help(pd.Series.dt.month)

Help on property:

    The month as January=1, December=12.
    
    Examples
    --------
    >>> datetime_series = pd.Series(
    ...     pd.date_range("2000-01-01", periods=3, freq="M")
    ... )
    >>> datetime_series
    0   2000-01-31
    1   2000-02-29
    2   2000-03-31
    dtype: datetime64[ns]
    >>> datetime_series.dt.month
    0    1
    1    2
    2    3
    dtype: int64



In [56]:
@pipeable
def month(col):
    """The month as January=1, December=12.
    
    Examples
    --------
    >>> datetime_series = pd.Series(
    ...     pd.date_range("2000-01-01", periods=3, freq="M")
    ... )
    >>> datetime_series
    0   2000-01-31
    1   2000-02-29
    2   2000-03-31
    dtype: datetime64[ns]
    >>> datetime_series.dt.month
    0    1
    1    2
    2    3
    dtype: int64

    """
    return col.dt.month

In [62]:
result = pd.Series(pd.date_range("2000-01-01", periods=12, freq="M"))
exp = Series(range(1,13))
result >> month()
#exp
#tm.assert_series_equal(result >> month(), exp)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [81]:
help(pd.Series.dt.week)

Help on property:

    The week ordinal of the year.
    
    .. deprecated:: 1.1.0
    
    Series.dt.weekofyear and Series.dt.week have been deprecated.
    Please use Series.dt.isocalendar().week instead.



In [87]:
datetime_series = pd.Series(pd.date_range("2000-01-01", periods=5, freq="W"))
datetime_series

#datetime_series.dt.week

0   2000-01-02
1   2000-01-09
2   2000-01-16
3   2000-01-23
4   2000-01-30
dtype: datetime64[ns]

In [ ]:
help(pd.Series.dt.month)

In [68]:
@pipeable
def quarter(col):
    """The quarter of the date.

    """
    return col.dt.quarter

In [77]:
result = pd.Series(pd.date_range("2000-01-01", periods=4, freq="Q"))
exp = Series(range(1,5))
exp
result >> quarter()
tm.assert_series_equal(result >>quarter(), exp)

In [63]:
#pip install pandas --upgrade

In [24]:
idx = pd.date_range("2012-01-01", "2015-01-01", freq="Y")

In [26]:
idx



array([ True, False, False])

In [27]:
idx.is_leap_year

array([ True, False, False])

In [80]:
datetime_series = pd.Series(pd.date_range("2000-01-01", periods=3, freq="Q"))
datetime_series.dt.quarter

0    1
1    2
2    3
dtype: int64

In [15]:
@pipeable
def is_leap_year(col):
    """Boolean indicator if the date belongs to a leap year.
    
    A leap year is a year, which has 366 days (instead of 365) including
    29th of February as an intercalary day.
    Leap years are years which are multiples of four with the exception
    of years divisible by 100 but not by 400.
    
    Returns
    -------
    Series or ndarray
         Booleans indicating if dates belong to a leap year.
    
    Examples
    --------
    This method is available on Series with datetime values under
    the ``.dt`` accessor, and directly on DatetimeIndex.
    
    >>> idx = pd.date_range("2012-01-01", "2015-01-01", freq="Y")
    >>> idx
    DatetimeIndex(['2012-12-31', '2013-12-31', '2014-12-31'],
                  dtype='datetime64[ns]', freq='A-DEC')
    >>> idx.is_leap_year
    array([ True, False, False])
    
    >>> dates_series = pd.Series(idx)
    >>> dates_series
    0   2012-12-31
    1   2013-12-31
    2   2014-12-31
    dtype: datetime64[ns]
    >>> dates_series.dt.is_leap_year
    0     True
    1    False
    2    False
    dtype: bool
    """
    return col.dt.is_leap_year

In [17]:
from datetime import (
    date,
    datetime,
    timedelta,
)

import numpy as np
import pytest
import pytz

from pandas._libs.tslibs import (
    iNaT,
    period as libperiod,
)
from pandas._libs.tslibs.ccalendar import (
    DAYS,
    MONTHS,
)
from pandas._libs.tslibs.np_datetime import OutOfBoundsDatetime
from pandas._libs.tslibs.parsing import DateParseError
from pandas._libs.tslibs.period import (
    INVALID_FREQ_ERR_MSG,
    IncompatibleFrequency,
)
from pandas._libs.tslibs.timezones import (
    dateutil_gettz,
    maybe_get_tz,
)
#from pandas.compat import np_datetime64_compat

import pandas as pd
from pandas import (
    NaT,
    Period,
    Timedelta,
    Timestamp,
    offsets,
)
import pandas._testing as tm

In [20]:
@pytest.mark.parametrize("freq", ["A", "M", "D", "H"])
def test_is_leap_year(self, freq):
    # GH 13727
    p = Period("2000-01-01 00:00:00", freq=freq)
    assert p.is_leap_year
    assert isinstance(p.is_leap_year, bool)

    p = Period("1999-01-01 00:00:00", freq=freq)
    assert not p.is_leap_year

    p = Period("2004-01-01 00:00:00", freq=freq)
    assert p.is_leap_year

    p = Period("2100-01-01 00:00:00", freq=freq)
    assert not p.is_leap_year

test_is_leap_year

<function __main__.test_is_leap_year(self, freq)>